version: '3.3'

volumes:
  static:
  media:

services:
  backend:
    build: ./backend/
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - ./docs/:/usr/share/nginx/html/api/docs/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/static/
      - media:/media/