# Generated by Django 3.2.3 on 2023-11-23 01:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231121_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombaseuser',
            name='subscribe',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
