# Generated by Django 3.2.3 on 2023-11-24 04:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_custombaseuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombaseuser',
            name='username',
            field=models.CharField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid username. This value may contain only English letters, numbers, and ./_ characters.', regex='^[\\w.-]+\\Z')]),
        ),
    ]
