# Generated by Django 3.2.3 on 2023-11-26 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_custombaseuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custombaseuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
