# Generated by Django 3.2.3 on 2023-11-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_custombaseuser_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='custombaseuser',
            constraint=models.CheckConstraint(check=models.Q(('username__exact', 'me')), name='name_not_me'),
        ),
    ]
