# Generated by Django 3.2.3 on 2023-11-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_custombaseuser_name_not_me'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='custombaseuser',
            name='name_not_me',
        ),
        migrations.AddConstraint(
            model_name='custombaseuser',
            constraint=models.CheckConstraint(check=models.Q(('username__exact', 'me'), _negated=True), name='name_not_me'),
        ),
    ]
