# Generated by Django 3.2.3 on 2023-11-30 00:15

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20231129_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombaseuser',
            name='first_name',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='custombaseuser',
            name='last_name',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='custombaseuser',
            name='username',
            field=models.CharField(max_length=75, unique=True, validators=[users.validators.validate_username]),
        ),
    ]
