# Generated by Django 3.2.3 on 2023-11-30 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20231130_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombaseuser',
            name='subscribe',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Объекты подписок'),
        ),
    ]
