# Generated by Django 3.2.3 on 2023-11-30 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_custombaseuser_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombaseuser',
            name='subscribe',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
