# Generated by Django 3.2.3 on 2023-12-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20231201_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombaseuser',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='custombaseuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='картинка пользователя'),
        ),
        migrations.AlterField(
            model_name='custombaseuser',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='фамилия'),
        ),
    ]
